os: osx
language: node_js
sudo: false
node_js:
- '6'
branches:
  only:
  - master
before_install:
- npm install -g gulp-cli
- npm install -g resume-cli
install:
- npm install
script:
- gulp
- gulp export
