dist: trusty
language: node_js
sudo: false
node_js:
  - '6'
branches:
  only:
  - master
addons:
chrome: stable
before_install:
  - npm install -g gulp
  - npm install -g resume-cli
install:
  - npm install
before_script:
  - npm link
script:
  - npm start
  - gulp
  - gulp export
deploy:
  provider: releases
  api_key:
    secure: "$GITHUB_API_KEY"
  file:
    - resume.pdf
  skip_cleanup: true
  on:
    repo: ayousif00/jsonresume-theme-caffeine
    tags: true
